baseurl: "www.lin23.online"
languageCode: zh-CN
title: 为学
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "日志"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "导航"
      url: "/nav/"
      weight: 3
    - name: "分类"
      url: "/categories/"
      weight: 4
    - name: "标签"
      url: "/tags/"
      weight: 5
    - name: "订阅"
      url: "/index.xml"

params:
  description: "天下事有难易乎？"
  footer: "&copy; Lin Gui 2021"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex","python"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true

